
CREATE TABLE game(
	id INT NOT NULL,
	last_played_at DATE,
	multiplayer BOOLEAN,
	item_id INT,
	FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE label(
  ID SERIAL PRIMARY KEY,
  name VARCHAR(30)
);


CREATE TABLE author(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL
	first_name varchar(150),
	last_name varchar(150),
);

CREATE TABLE book(
  ID SERIAL PRIMARY KEY,
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL,
  publisher VARCHAR(30) NOT NULL,
  cover_state VARCHAR(10) NOT NULL,
  label_ID INT,
  author_ID INT,
  genre_ID INT,
  FOREIGN KEY (label_ID) REFERENCES label(ID),
  FOREIGN KEY (author_ID) REFERENCES author(ID),
  FOREIGN KEY(genre_ID) REFERENCES genre(ID)
);