
CREATE TABLE game(
	id INT NOT NULL,
	last_played_at DATE,
	multiplayer BOOLEAN,
	item_id INT,
	FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE author(
	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL
	first_name varchar(150),
	last_name varchar(150),
);